In [312]:
import pandas as pd
import numpy as np
from fuzzywuzzy import fuzz
from sqlalchemy import create_engine
import psycopg2
from sqlalchemy import Column, Integer, Float, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy import UniqueConstraint, ForeignKey
from sqlalchemy.orm import relationship
import config

In [313]:
const_col_id = 'id'
const_col_country = 'country'
const_col_country_id = 'country_id'
const_col_covid_deaths = 'covid_deaths'
const_col_covid_confirmed = 'covid_confirmed'
const_col_region = 'region'
const_col_population = 'population'
const_col_health_expenditure = 'health_expenditure'

In [314]:
# Primary data source of the analyisis is Health expenditure of countries. WHich ever the countries had this information
# is considered as the primary source, hence all other sources are filtered based on this list.

health_expdf =  pd.read_csv('Health Expenditure by Country.csv')  
health_expdf.head()
countryDF = health_expdf[['Country']].copy()
countryDF.rename(columns={"Country": const_col_country}, inplace = True)
# Make the country name upper case
countryDF[const_col_country] = countryDF[const_col_country].str.upper()
countryDF.index = np.arange(1, len(countryDF)+1)
countryDF.index.name = const_col_id
countryDF.head()

      country
id
1   AUSTRALIA
2     AUSTRIA
3     BELGIUM
4      CANADA
5       CHILE

In [315]:
health_expdf.rename(columns={"Country":const_col_country}, inplace = True)
health_expdf[const_col_country_id] = health_expdf.apply (lambda row: get_countryID(row[const_col_country]), axis=1)
health_expdf = health_expdf.loc[health_expdf.country_id >0]
health_expdf = health_expdf[[const_col_country_id,const_col_health_expenditure]]
health_expdf.dropna()
health_expdf.index = np.arange(1, len(health_expdf)+1)
health_expdf.head()

   country_id  health_expenditure
1           1               9.334
2           2              10.408
3           3              10.349
4           4              10.790
5           5               9.102

In [316]:
def get_countryID(countryname):
    countryID = 0    
    selectedCountry = countryDF.loc[countryDF.country == countryname.upper()]
    if(len(selectedCountry) > 0):
        countryID = selectedCountry.index.values.astype(int)[0]
    else:
        bestmatchscore = 0
        matchscore = 0
        bestmatchcountry = ''
        for index, row in countryDF.iterrows():
            matchscore = fuzz.ratio(countryname.upper(), row[const_col_country])

            if (matchscore > bestmatchscore):
                bestmatchscore = matchscore
                bestmatchcountry = row[const_col_country]
        if (bestmatchscore> 80):
            selectedCountry = countryDF.loc[countryDF.country == bestmatchcountry.upper()]
            countryID = selectedCountry.index.values.astype(int)[0]
        else:
            name_parts = countryname.split(' ') 
            if(len(name_parts)>1):
                for part in name_parts:
                    countryID = get_countryID(part)
                    if (countryID > 0):
                        break
            elif(len(countryname) < 4):
                # check for scenario US = United States                                
                for index, row in countryDF.iterrows():
                    shortname = ''
                    name_parts = row[const_col_country].split(' ')                    
                    if(len(name_parts) > 1):
                        #take the first letter of the word
                        for part in name_parts:
                            shortname = shortname + part[0]                        
                        if(shortname == countryname.upper()):
                            selectedCountry = countryDF.loc[countryDF.country == row[const_col_country]]
                            countryID = selectedCountry.index.values.astype(int)[0]
                            break                            

    return countryID

In [317]:
Covid_deathdf =  pd.read_csv('Covid_stats.csv')

Covid_deathdf[const_col_country_id] = Covid_deathdf.apply (lambda row: get_countryID(row[const_col_country]), axis=1)
Covid_deathdf = Covid_deathdf.loc[Covid_deathdf.country_id >0]
Covid_deathdf = Covid_deathdf[[const_col_country_id,const_col_covid_deaths,const_col_covid_confirmed]]
Covid_deathdf.dropna()
Covid_deathdf.index = np.arange(1, len(Covid_deathdf)+1)
Covid_deathdf.head()

   country_id  covid_deaths  covid_confirmed
1           1           361            22358
2           2           724            22439
3           3          9900            75647
4           4          9052           122703
5           5         10205           378168

In [318]:
populationDF =  pd.read_csv('Population.csv')
populationDF[const_col_country_id] = populationDF.apply (lambda row: get_countryID(row[const_col_country]), axis=1)
populationDF = populationDF.loc[populationDF.country_id >0]

# since data source have a seeprate record for seperate geographically placed territories of the same country, we just remove the smaller populated record
populationDF.sort_values([const_col_country_id, const_col_population], ascending=[True, False], inplace = True)
populationDF.drop_duplicates(subset=const_col_country_id, keep='first', inplace=True)
populationDF = populationDF[[const_col_country_id,const_col_region,const_col_population]]
populationDF.dropna()
populationDF.index = np.arange(1, len(populationDF)+1)
populationDF.head()

   country_id    region  population
1           1   Oceania    25203198
2           2    Europe     8955102
3           3    Europe    11539328
4           4  Americas    37411047
5           5  Americas    18952038

In [319]:
Base = declarative_base()
uid = config.username
pwd = config.password
Engine = create_engine(f"postgresql://{uid}:{pwd}@127.0.0.1/Covid_Analysis")

class Country(Base):
    __tablename__ = 'country'
    __table_args__ = (UniqueConstraint(const_col_country),)
    id = Column(Integer, primary_key=True)
    country = Column(String, nullable=False)

class Covid_Counts(Base):
    __tablename__ = 'covid_counts'
    id = Column(Integer, primary_key=True)
    country_id = Column(Integer, ForeignKey('country.id'), nullable=False)
    covid_deaths = Column(Integer, nullable=False)
    covid_confirmed = Column(Integer, nullable=False)
    
class Population(Base):
    __tablename__ = 'population'
    id = Column(Integer, primary_key=True)
    country_id = Column(Integer, ForeignKey('country.id'), nullable=False)
    region = Column(String, nullable=False)    
    population = Column(Integer, nullable=False)

class HealthExpenditure(Base):
    __tablename__ = 'health_expenditure'
    id = Column(Integer, primary_key=True)
    country_id = Column(Integer, ForeignKey('country.id'), nullable=False)
    health_expenditure = Column(Float, nullable=False)    
    
Base.metadata.drop_all(Engine)
Base.metadata.create_all(Engine)

with Engine.connect() as dbcon:
    with dbcon.begin() as dbtrans:
        dbcon.execute(Country.__table__.insert(), countryDF.to_dict(orient='records'))
        dbcon.execute(Covid_Counts.__table__.insert(), Covid_deathdf.to_dict(orient='records'))
        dbcon.execute(Population.__table__.insert(), populationDF.to_dict(orient='records'))
        dbcon.execute(HealthExpenditure.__table__.insert(), health_expdf.to_dict(orient='records'))
        dbtrans.commit()